// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-gjn8OtBz5QaUjoCkDVzJPo3DCPAPu0',
    appId: '1:213182381352:web:382220c086f2e8057b241d',
    messagingSenderId: '213182381352',
    projectId: 'ampera-saiyo',
    authDomain: 'ampera-saiyo.firebaseapp.com',
    storageBucket: 'ampera-saiyo.firebasestorage.app',
    measurementId: 'G-ES1VLM0PJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2f6hxkcTs-R3Ih-78lywKyo9lLizCLO0',
    appId: '1:213182381352:android:95bd8a112d040e257b241d',
    messagingSenderId: '213182381352',
    projectId: 'ampera-saiyo',
    storageBucket: 'ampera-saiyo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-gjn8OtBz5QaUjoCkDVzJPo3DCPAPu0',
    appId: '1:213182381352:web:002eab0637e502747b241d',
    messagingSenderId: '213182381352',
    projectId: 'ampera-saiyo',
    authDomain: 'ampera-saiyo.firebaseapp.com',
    storageBucket: 'ampera-saiyo.firebasestorage.app',
    measurementId: 'G-7DGREXD382',
  );
}
